# Usage: ansible-playbook -i ec2.py -e app_name=lake-home -e app_path=~/Documents/dev/app/ aws-install-docker-compose-app.yml

---

- hosts: "tag_Name_ansible-static-webserver-{{ app_name }}"
  roles:
    - install-docker-compose-app

