# Installs Docker and docker-compose
---
# From official instructions to install Docker on Ubuntu http://docs.docker.com/engine/installation/ubuntulinux/#installation
- name: Add docker keyserver
  apt_key: keyserver=hkp://p80.pool.sks-keyservers.net:80 id=58118E89F3A912897C070ADBF76221572C52609D
  sudo: True

- name: Add docker repo
  apt_repository: repo='deb https://apt.dockerproject.org/repo ubuntu-trusty main' state=present
  sudo: True

- name: Install docker
  apt: pkg=docker-engine update_cache=yes
  sudo: True

- name: Add ssh user to docker group
  command: usermod -aG docker {{ ansible_ssh_user }}
  sudo: True
  register: user_task

- name: Ensure docker is started
  service: name=docker state=started

- name: Install pip for docker-compose
  apt: pkg=python-pip
  sudo: True

- name: Upgrade to latest pip (otherwise run into 'requests' library error)
  pip: name=pip state=latest
  sudo: True

- name: Install docker-compose
  pip: name=docker-compose
  sudo: True
